### PR TITLE
fix: Migrate to operator-sdk 1.11

### LINKED ISSUE #16: Operator projects using the removed APIs in k8s 1.22 requires changes.
### Problem Description

Kubernetes has been deprecating API(s), which will be removed and are no longer available in 1.22. Operators projects using [these APIs](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22) versions will **not** work on Kubernetes 1.22 or any cluster vendor using this Kubernetes version(1.22), such as OpenShift 4.9+. Following the APIs that are most likely your projects to be affected by:
- apiextensions.k8s.io/v1beta1: (Used for CRDs and available since v1.16)
- rbac.authorization.k8s.io/v1beta1: (Used for RBAC/rules and available since v1.8)
- admissionregistration.k8s.io/v1beta1 (Used for Webhooks and available since v1.16)

Therefore, looks like this project distributes solutions in the [repository](https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/atlasmap-operator) and does not contain any version compatible with k8s 1.22/OCP 4.9. ([More info](https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/138)). Following some findings by checking the distributions published:

- **atlasmap-operator.v0.1.0**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["atlasmaps.atlasmap.io"]) 
- **atlasmap-operator.v0.2.0**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["atlasmaps.atlasmap.io"]) 
- **atlasmap-operator.v0.3.0**: this distribution is using APIs which were deprecated and removed in v1.22. More info: https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22. Migrate the API(s) for CRD: (["atlasmaps.atlasmap.io"]) 

**NOTE:** The above findings are only about the manifests shipped inside of the distribution. It is not checking the codebase.

### How to solve

It would be very nice to see new distributions of this project that are no longer using [these APIs](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22) and so they can work on Kubernetes 1.22 and newer and published in the [community-operators](https://github.com/redhat-openshift-ecosystem/community-operators-prod/tree/main/operators/atlasmap-operator) collection. OpenShift 4.9, for example, will not ship operators anymore that do still use v1beta1 extension APIs.

Due to the number of options available to build Operators, it is hard to provide direct guidance on updating your operator to support Kubernetes 1.22. Recent versions of the [OperatorSDK](https://github.com/operator-framework/operator-sdk) greater than [1.0.0](https://github.com/operator-framework/operator-sdk/releases) and [Kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) greater than [3.0.0](https://github.com/kubernetes-sigs/kubebuilder/releases) scaffold your project with the latest versions of these APIs (all that is generated by tools only). See the guides to upgrade your projects with OperatorSDK [Golang](https://sdk.operatorframework.io/docs/building-operators/golang/migration/), [Ansible](https://sdk.operatorframework.io/docs/building-operators/ansible/migration/), [Helm](https://sdk.operatorframework.io/docs/building-operators/helm/migration/) or the [Kubebuilder](https://book.kubebuilder.io/migration/v2vsv3.html) one. For APIs other than the ones mentioned above, you will have to check your code for usage of removed API versions and upgrade to newer APIs. The details of this depend on your codebase.

**If this projects only need to migrate the API for CRDs and it was built with [OperatorSDK](https://github.com/operator-framework/operator-sdk) versions lower than [1.0.0](https://github.com/operator-framework/operator-sdk/releases) then, you maybe able to solve it with an [OperatorSDK](https://github.com/operator-framework/operator-sdk) version >= v0.18.x < 1.0.0:**

> $ operator-sdk generate crds --crd-version=v1
> INFO[0000] Running CRD generator.                       
> INFO[0000] CRD generation complete.

**Alternatively, you can try to upgrade your manifests with [controller-gen](https://book.kubebuilder.io/reference/controller-gen.html) ([version >= v0.4.1](https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.4.1)) :**

#### If this project does not use Webhooks:

> $ controller-gen crd:trivialVersions=true,preserveUnknownFields=false rbac:roleName=manager-role  paths="./..."

#### If this project is using Webhooks:

1. Add the markers [sideEffects](https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/webhook/parser.go#L81) and [admissionReviewVersions](https://github.com/kubernetes-sigs/controller-tools/blob/master/pkg/webhook/parser.go#L114) to your webhook (Example with sideEffects=None and admissionReviewVersions={v1,v1beta1}: [memcached-operator/api/v1alpha1/memcached_webhook.go](https://github.com/operator-framework/operator-sdk/blob/master/testdata/go/v3/memcached-operator/api/v1alpha1/memcached_webhook.go#L39)):

2. Run the command:
> $ controller-gen crd:trivialVersions=true,preserveUnknownFields=false rbac:roleName=manager-role webhook paths="./..."

For further information and tips see the [comment](https://github.com/redhat-openshift-ecosystem/community-operators-prod/discussions/138#discussioncomment-1245759).

### PR DESCRIPTION
**Pull request by igarashitm**
Fixes: #16

I'm trying to migrate to operator-sdk 1.11 by following official document
https://sdk.operatorframework.io/docs/building-operators/golang/migration/

Submitting a draft PR to just make it visible - there are more to do, not straight forward.

### CODE REVIEW

**Comment by igarashitm** [comment]
#### Questions
* Should we check in `vendor/` directory?
It looks like a maven repo or node_modules equivalent, so I thought the answer was definitively NO, but searching in internet it's not really definitive...
* What's the migrate path for the `(client.Writer).Create()` argument type change from `runtime.Object` to `client.Object`
This gets compilation error - https://github.com/atlasmap/atlasmap-operator/pull/17/files#diff-b7d0527d86f512bbcc4703d6d5da9ce7d44e5ed2e40efbbff7c3f72881001023L82
* Are the `action` code really required with latest operator-sdk? - Files which used to be under `/pkg/controller/atlasmap`, are these some generated code from older SDK? - https://github.com/atlasmap/atlasmap-operator/pull/17/files#diff-b7d0527d86f512bbcc4703d6d5da9ce7d44e5ed2e40efbbff7c3f72881001023
* `/pkg/config/config.go` says it's generated code, could it be removed and read from yaml directly instead?
* How about `/pkg/util` and `/version`? could these be eliminated with newer SDK?

**Comment by phantomjinx** [comment]
This branch has a commit on top of PR/17 that tops off this migration work.
- Adds and modifies the Makefile with variables, extra rules and functionality;
- Can build, deploy, push, install and bundle from Makefile

https://github.com/phantomjinx/atlasmap-operator/tree/deprecation

> #### Questions
> 
>     * Should we check in `vendor/` directory?
Yes. Allows for dependencies to be always available when users download.

>     * What's the migrate path for the `(client.Writer).Create()` argument type change from `runtime.Object` to `client.Object`
Straight change from 1 to the other worked okay for compilation.

>     * Are the `action` code really required with latest operator-sdk?
Yes. The actions govern the installation and monitoring of the operand resources. The operator-sdk upgrade has little bearing on this.
The 'new' operator-sdk layout encourages a much flatter code structure so have moved everything to controllers.

>     * `/pkg/config/config.go` says it's generated code, could it be removed and read from yaml directly instead?
It may have been generated to start with but still very much required as it contains config settings for operands. Syndesis does have a yaml file with actual values but also has a go file for the schema. So a yaml file can be introduced but doesn't really give you much at the moment.

>     * How about `/pkg/util` and `/version`? could these be eliminated with newer SDK?
Migrated util to controllers/ but have removed version and subsumed into controller code.

**Comment by igarashitm** [comment]
@phantomjinx thank you for the really quick work!!

**Comment by phantomjinx** [comment]
No worries.

**Comment by phantomjinx** [comment]
Tests seem to be failing because of GLIB. Normally, this is a problem with building and is solved by
`CGO_ENABLED=0 go build` [1]

However, its failing on the controller-gen execution phase. So maybe the same solution but not sure.

[1] https://stackoverflow.com/questions/64421305/heroku-go-app-crashes-version-glibc-2-32-not-found-required-by-bin-main

**Comment by igarashitm** [comment]
The culprit for the glibc version error was the controller-gen binary checked-in under `bin/` - removed it but then got an another error
> Error: ../../../go/pkg/mod/k8s.io/client-go@v0.22.1/plugin/pkg/client/auth/exec/metrics.go:21:2: package io/fs is not in GOROOT (/opt/hostedtoolcache/go/1.15.15/x64/src/io/fs)

I'll try to explicitly specify go-1.16 in the GH action.

**Comment by igarashitm** [comment]
OK passed, merged - thank you again for the help @phantomjinx !

**Pull request merged**
