### PR TITLE
migration to go mod

### PR DESCRIPTION
**Pull request by akoserwal**
Migrating to go mod

### CODE REVIEW

**Comment by jamesnetherton** [comment]
We should also be able to remove the `vendor` directory, right?

**Comment by akoserwal** [comment]
yes

**Comment by jamesnetherton** [comment]
I reverted this change. 

The operator-sdk needs updating to support go modules.

I can try to take a look at doing this next week. Otherwise, you are free to create another PR if you'd like to work on it.

**Comment by akoserwal** [comment]
@jamesnetherton : I was planning to submit another pr with upgraded operator-sdk version. I can work on it. make sense

**Pull request merged**
